apiVersion: v1
kind: ConfigMap
metadata:
  name: qs-order-mgr-cm
data:
  APP_VERSION: 0.0.1
  KAFKA_BOOTSTRAP_SERVERS: dev-kafka-bootstrap.smq-dev.svc:9093
  ORDER_TOPIC: qs-orders
  KAFKA_SSL_PROTOCOL: TLSv1.2
  KAFKA_SSL_TRUSTSTORE_LOCATION: /deployments/certs/server/ca.p12
  KAFKA_SSL_TRUSTSTORE_TYPE: PKCS12
  KAFKA_SSL_KEYSTORE_LOCATION: /deployments/certs/user/user.p12
  KAFKA_SSL_KEYSTORE_TYPE: PKCS12
  KAFKA_SECURITY_PROTOCOL: SSL
  

  